version: 2
jobs:
  build:
    docker:
      - image: vigemus/lua:luarocks-5.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: bin/pctl setup
      - run:
          name: Unit Tests
          command: bin/pctl tests
